#dns监听端口
bind [::]:5335

#bootstrap DNS
server tls://223.5.5.5 -bootstrap-dns
server tls://119.29.29.29 -bootstrap-dns
server tls://223.6.6.6 -bootstrap-dns
server tls://8.8.8.8 -bootstrap-dns

### Default Group 默认分组，保证非CN域名正常解析
server-https https://1.0.0.1/dns-query
server-https https://1.1.1.1/dns-query
server-https https://8.8.8.8/dns-query
server-https https://8.8.4.4/dns-query
server 1.0.0.1
server 8.8.4.4 
server 1.1.1.1
server 8.8.8.8
server 2606:4700:4700::1111
server 2606:4700:4700::1001
server 2001:4860:4860::8888
server 2001:4860:4860::8844

# 专属 DNS 组（解析谷歌商店地址）
server 1.0.0.1 -group special_dns
server 1.1.1.1 -group special_dns

# 谷歌商店地址走 special_dns 组
nameserver /xn--ngstr-lra8j.com/special_dns
nameserver /clientservices.googleapis.com/special_dns
nameserver /googleapis.cn/special_dns
nameserver /googleapis.com/special_dns
nameserver /services.googleapis.com/special_dns


### Domestic Group 用于解析 CN 域名,可以通过-subnet添加edns子网
server-https https://223.5.5.5/dns-query -group domestic -exclude-default-group
server-https https://223.6.6.6/dns-query -group domestic -exclude-default-group

#配置分流规则
domain-set -name cn -file '/data/other_vol/china-list.txt'
domain-rules /domain-set:cn/ -nameserver domestic

#测速模式
speed-check-mode ping,tcp:80,tcp:443

#双栈优选Ipv4还是ipv6快
dualstack-ip-selection yes
dualstack-ip-selection-threshold 15

#缓存预获取
prefetch-domain yes

#乐观缓存
serve-expired yes

#DNS缓存持久化
cache-size 30000
cache-persist yes
cache-file /data/other_vol/smartdns/cache
cache-checkpoint-time 3600

#配置过期缓存响应TTL
serve-expired-reply-ttl 5

# 开启过期缓存服务 (即刻响应过期缓存，后台异步更新)
serve-expired yes
serve-expired-ttl 30000
serve-expired-reply-ttl 3

# 所有资源记录的 TTL
rr-ttl-min 600
rr-ttl-max 86400
rr-ttl-reply-max 60
